/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author zvcesar
 */
public class GUI_InformacionAuto extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionAuto
     */
    public GUI_InformacionAuto() {
        initComponents();
        
    }
    public void devolverNumeroRegistro()
    {
      jt_NumeroRegistro.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NumeroRegistro = new javax.swing.JLabel();
        jl_NombreDueño = new javax.swing.JLabel();
        jl_CedulaDueño = new javax.swing.JLabel();
        jl_PlacaAuto = new javax.swing.JLabel();
        jt_NumeroRegistro = new javax.swing.JTextField();
        jt_NombreDueño = new javax.swing.JTextField();
        jt_CedulaDueño = new javax.swing.JTextField();
        jt_PlacaAuto = new javax.swing.JTextField();

        jl_NumeroRegistro.setText("Numero de Registro");

        jl_NombreDueño.setText("Nombre del Dueño");

        jl_CedulaDueño.setText("Cedula del dueño");

        jl_PlacaAuto.setText("Placa del Automovil");

        jt_CedulaDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CedulaDueñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_PlacaAuto)
                            .addComponent(jl_CedulaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_CedulaDueño, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jt_PlacaAuto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_NumeroRegistro)
                            .addComponent(jl_NombreDueño))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_NumeroRegistro)
                            .addComponent(jt_NombreDueño))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NumeroRegistro)
                    .addComponent(jt_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreDueño)
                    .addComponent(jt_NombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CedulaDueño)
                    .addComponent(jt_CedulaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_PlacaAuto)
                    .addComponent(jt_PlacaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CedulaDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CedulaDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CedulaDueñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_CedulaDueño;
    private javax.swing.JLabel jl_NombreDueño;
    private javax.swing.JLabel jl_NumeroRegistro;
    private javax.swing.JLabel jl_PlacaAuto;
    private javax.swing.JTextField jt_CedulaDueño;
    private javax.swing.JTextField jt_NombreDueño;
    private javax.swing.JTextField jt_NumeroRegistro;
    private javax.swing.JTextField jt_PlacaAuto;
    // End of variables declaration//GEN-END:variables
    public void setJtNumeroRegistro()
    {
      this.jt_NumeroRegistro.setText(" ");
    }
    public void setJtCedulaDueño()
    {
      this.jt_CedulaDueño.setText(" ");
    }
    public void setJtNombreDueño()
    {
      this.jt_NombreDueño.setText(" ");
    }
    public void setJtPlacaAuto()
    {
      this.jt_PlacaAuto.setText(" ");
    }
    public String getJtNumeroRegistro()
    {
        return jt_NumeroRegistro.getText();
    }
    public String getJtCedulaDueño()
    {
        return jt_CedulaDueño.getText();
    }
    public String getJtNNombreDueño()
    {
        return jt_NombreDueño.getText();
    }
    public String getJtPlacaAuto()
    {
        return jt_PlacaAuto.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
      jt_CedulaDueño.setText(arreglo[1]);
      jt_NombreDueño.setText(arreglo[2]);
      jt_PlacaAuto.setText(arreglo[3]);
    }
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[4];
        arreglo[0]=this.jt_NumeroRegistro.getText();
        arreglo[1]=this.jt_CedulaDueño.getText(); 
        arreglo[2]=this.jt_NombreDueño.getText();
        arreglo[3]=this.jt_PlacaAuto.getText();
        
        return arreglo;
    }
    public void limpiar()
    {
      jt_NombreDueño.setText(" ");
      jt_CedulaDueño.setText(" ");
      jt_PlacaAuto.setText(" ");
    }
    public void estadoInicial()
    {
      jt_NombreDueño.setEnabled(false);
      jt_CedulaDueño.setEnabled(false);
      jt_PlacaAuto.setEnabled(false);
    }
    public void habilitarAgregar()
    {
      jt_NombreDueño.setEnabled(true);
      jt_CedulaDueño.setEnabled(true);
      jt_PlacaAuto.setEnabled(true);  
    }
    public String generarRegistro(boolean agregar, int registro)
    {
     if(agregar)
     {
      registro++;   
     }
     else 
     {
         registro=1;
     }
     
     return ""+registro;
        
    }
    public void colocarRegistro(boolean agregar, int registro)
    {
     jt_NumeroRegistro.setText(generarRegistro(agregar, registro));
    }
}
